version: '2'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=gerenciapontos
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha
      - MAX_CONNECTIONS=300
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/setup.sql
